# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import drone_pb2 as drone__pb2


class DronePositionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.registerClients = channel.unary_unary(
        '/DronePosition/registerClients',
        request_serializer=drone__pb2.Droneid.SerializeToString,
        response_deserializer=drone__pb2.Droneid.FromString,
        )
    self.getPosition = channel.unary_stream(
        '/DronePosition/getPosition',
        request_serializer=drone__pb2.Droneid.SerializeToString,
        response_deserializer=drone__pb2.Coordinates.FromString,
        )


class DronePositionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def registerClients(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DronePositionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'registerClients': grpc.unary_unary_rpc_method_handler(
          servicer.registerClients,
          request_deserializer=drone__pb2.Droneid.FromString,
          response_serializer=drone__pb2.Droneid.SerializeToString,
      ),
      'getPosition': grpc.unary_stream_rpc_method_handler(
          servicer.getPosition,
          request_deserializer=drone__pb2.Droneid.FromString,
          response_serializer=drone__pb2.Coordinates.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DronePosition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
