# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drone.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x64rone.proto\".\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"\x15\n\x07\x44roneid\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x63\n\rDronePosition\x12\'\n\x0fregisterClients\x12\x08.Droneid\x1a\x08.Droneid\"\x00\x12)\n\x0bgetPosition\x12\x08.Droneid\x1a\x0c.Coordinates\"\x00\x30\x01\x62\x06proto3')
)




_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Coordinates.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Coordinates.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Coordinates.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=61,
)


_DRONEID = _descriptor.Descriptor(
  name='Droneid',
  full_name='Droneid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Droneid.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.message_types_by_name['Droneid'] = _DRONEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATES,
  __module__ = 'drone_pb2'
  # @@protoc_insertion_point(class_scope:Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)

Droneid = _reflection.GeneratedProtocolMessageType('Droneid', (_message.Message,), dict(
  DESCRIPTOR = _DRONEID,
  __module__ = 'drone_pb2'
  # @@protoc_insertion_point(class_scope:Droneid)
  ))
_sym_db.RegisterMessage(Droneid)



_DRONEPOSITION = _descriptor.ServiceDescriptor(
  name='DronePosition',
  full_name='DronePosition',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=86,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='registerClients',
    full_name='DronePosition.registerClients',
    index=0,
    containing_service=None,
    input_type=_DRONEID,
    output_type=_DRONEID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getPosition',
    full_name='DronePosition.getPosition',
    index=1,
    containing_service=None,
    input_type=_DRONEID,
    output_type=_COORDINATES,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRONEPOSITION)

DESCRIPTOR.services_by_name['DronePosition'] = _DRONEPOSITION

# @@protoc_insertion_point(module_scope)
